modLoader="javafml"
loaderVersion="[40,)"
issueTrackerURL="https://github.com/Verph/astikor-carts-tfc/issues"
license="MIT"

[[mods]]
modId="tfcastikorcarts"
version="${file.jarVersion}"
displayName="TFC Astikor Carts"
displayURL="https://www.curseforge.com/minecraft/mc-mods/astikor-carts-tfc"
authors="MennoMax, pau101, Verph"
description="Bringing the carts to TFC."

[[dependencies.tfcastikorcarts]]
    modId = "astikorcarts"
    mandatory = true
    versionRange = "[1,)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.tfcastikorcarts]]
	mandatory = true
	modId = "tfc"
	ordering = "AFTER"
	side = "BOTH"
	versionRange = "[1.20.1-3,)"
	
[[dependencies.tfcastikorcarts]]
    modId = "forge"
    mandatory = true
    versionRange = "[47.1.3,47.1.36)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.tfcastikorcarts]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.20.1,1.20.2)"
    ordering = "NONE"
    side = "BOTH"
